version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "eu-central-1"
    REPOSITORY_URI: "070503547773.dkr.ecr.eu-central-1.amazonaws.com/ci-cd-demo"

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - pip install awscli
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      
  build:
    commands:
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
